### ISSUE TITLE
Please explain how to deploy to developer environment

### ISSUE THREAD

**Issue by VR-Architect** [Bonitasoft-Community/page_containership#1]
Nice work! 

Can you please explain how to deploy to v7.2.2 community edition? I was not able to import as it said it was missing a json file.

**Comment by pierre-yves-monnet** [comment]
Thanks !
The point is this custom page is use to manage Tenant, which is a Subscription function. So even if you deploy it on a Community edition, it will failed during the call because the method does not exist.

I'm stil curious : which error do you have during the import ?  Which file is missing ?
